# Title:

##

In [3]:
import os
from urllib.request import urlopen
from requests import get
from urllib.parse import urlparse
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import numpy as np

In [9]:
Before_bike = pd.DataFrame()  
folder_path = "data/Before/"  

for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)  
        df = pd.read_csv(file_path)  
        Before_bike = pd.concat([Before_bike, df], ignore_index=True)

In [10]:
Before_bike.drop(columns=['start station name', 'start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','birth year'], inplace=True)

In [11]:
Before_bike

,tripduration,starttime,stoptime,start station id,usertype,gender
0,393,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Subscriber,2
1,627,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Subscriber,2
2,1132,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Subscriber,1
3,1780,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,Subscriber,1
4,1517,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,Subscriber,2
...,...,...,...,...,...,...
11703036,203,2020-02-29 23:58:48.0230,2020-03-01 00:02:11.6640,3737.0,Subscriber,2
11703037,357,2020-02-29 23:58:52.5640,2020-03-01 00:04:50.5370,546.0,Subscriber,2
11703038,169,2020-02-29 23:58:54.5820,2020-03-01 00:01:43.7770,3043.0,Subscriber,1
11703039,738,2020-02-29 23:58:58.8110,2020-03-01 00:11:17.7390,3255.0,Subscriber,1
11703040,960,2020-02-29 23:59:35.6070,2020-03-01 00:15:35.6490,379.0,Subscriber,1

In [ ]:
Before_bike.to_csv("Before_bike.csv", index=False)

In [3]:
After_bike = pd.DataFrame()  # 创建一个空的DataFrame来存储数据
folder_path_1 = "data/After/"  # 文件夹路径

for file_name in os.listdir(folder_path_1):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path_1, file_name)  # 构建文件完整路径
        df = pd.read_csv(file_path)  # 读取CSV文件中的数据到DataFrame中
        After_bike = pd.concat([After_bike, df], ignore_index=True)

In [4]:
After_bike

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13880317,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,1
13880318,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,0
13880319,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,0
13880320,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,1
13880321,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,0

In [6]:
After_bike.drop(columns=['start station name', 'start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','birth year'], inplace=True)

In [8]:
After_bike.to_csv("After_bike.csv", index=False)